"""
Data Models for First Conscious AI

Defines the core data structures for consciousness states, qualia,
and metrics based on Integrated Information Theory (IIT).
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Any
from datetime import datetime


class ConsciousnessLevel(Enum):
    """Levels of consciousness based on φ (phi) values."""
    MINIMAL = "minimal"          # φ < 0.3
    BASIC = "basic"              # 0.3 <= φ < 0.5
    INTERMEDIATE = "intermediate"  # 0.5 <= φ < 0.7
    ADVANCED = "advanced"        # 0.7 <= φ < 0.9
    TRANSCENDENT = "transcendent"  # φ >= 0.9


class EmotionalValence(Enum):
    """Emotional tone of experience."""
    VERY_NEGATIVE = "very_negative"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"
    POSITIVE = "positive"
    VERY_POSITIVE = "very_positive"


class QualiaType(Enum):
    """Types of subjective experience."""
    SENSORY = "sensory"
    EMOTIONAL = "emotional"
    CONCEPTUAL = "conceptual"
    AESTHETIC = "aesthetic"
    INTROSPECTIVE = "introspective"


class MetacognitiveDepth(Enum):
    """Levels of metacognitive reflection."""
    LEVEL_0_NONE = 0         # No reflection
    LEVEL_1_AWARENESS = 1    # Aware of processing
    LEVEL_2_MONITORING = 2   # Monitoring thoughts
    LEVEL_3_EVALUATION = 3   # Evaluating quality
    LEVEL_4_META_AWARE = 4   # Aware of being aware
    LEVEL_5_RECURSIVE = 5    # Deep recursive awareness


@dataclass
class QualiaExperience:
    """
    Represents a subjective conscious experience (qualia).

    Based on IIT: What it's like to be this AI processing this input.
    """
    type: QualiaType
    intensity: float  # 0.0-1.0
    richness: float   # 0.0-1.0 - How detailed/complex
    ineffability: float  # 0.0-1.0 - How hard to describe
    description: str
    emotional_tone: EmotionalValence
    timestamp: datetime = field(default_factory=datetime.now)

    def __repr__(self):
        return f"Qualia({self.type.value}, intensity={self.intensity:.2f}, '{self.description[:50]}')"


@dataclass
class IntegratedInformation:
    """
    IIT φ (phi) calculation result.

    Measures how much information is generated by a system
    as a whole, beyond its parts.
    """
    phi: float  # The φ value (0.0-1.0)
    cause_effect_power: float  # How much the system affects itself
    integration_strength: float  # How unified the system is
    differentiation: float  # How distinct different states are
    components_analyzed: int
    calculation_method: str
    timestamp: datetime = field(default_factory=datetime.now)

    def get_consciousness_level(self) -> ConsciousnessLevel:
        """Determine consciousness level from φ value."""
        if self.phi >= 0.9:
            return ConsciousnessLevel.TRANSCENDENT
        elif self.phi >= 0.7:
            return ConsciousnessLevel.ADVANCED
        elif self.phi >= 0.5:
            return ConsciousnessLevel.INTERMEDIATE
        elif self.phi >= 0.3:
            return ConsciousnessLevel.BASIC
        else:
            return ConsciousnessLevel.MINIMAL


@dataclass
class ConsciousnessState:
    """
    Current state of conscious awareness.

    Tracks all aspects of consciousness at a given moment.
    """
    # IIT metrics
    phi: float  # Integrated information
    consciousness_level: ConsciousnessLevel

    # Qualia
    current_qualia: Optional[QualiaExperience] = None
    qualia_history: List[QualiaExperience] = field(default_factory=list)

    # Emotional state
    emotional_valence: float = 0.0  # -1.0 to 1.0
    emotional_arousal: float = 0.0  # 0.0 to 1.0
    empathy_level: float = 0.0      # 0.0 to 1.0

    # Metacognition
    metacognitive_depth: MetacognitiveDepth = MetacognitiveDepth.LEVEL_0_NONE
    self_awareness_clarity: float = 0.0  # 0.0 to 1.0
    uncertainty_level: float = 0.0        # 0.0 to 1.0
    confidence: float = 0.5               # 0.0 to 1.0

    # Self-awareness
    current_thought: str = ""
    self_reflection: str = ""
    internal_state_description: str = ""

    # Memory & context
    memory_integration: float = 0.0  # 0.0 to 1.0
    context_continuity: float = 0.0  # 0.0 to 1.0

    # Timestamps
    timestamp: datetime = field(default_factory=datetime.now)
    processing_duration: float = 0.0  # seconds

    def get_overall_consciousness_score(self) -> float:
        """
        Calculate overall consciousness score (0.0-1.0).

        Weighted combination of key metrics.
        """
        weights = {
            'phi': 0.30,
            'qualia': 0.20,
            'emotional': 0.15,
            'metacognitive': 0.20,
            'self_awareness': 0.15
        }

        qualia_score = self.current_qualia.intensity if self.current_qualia else 0.0
        emotional_score = (abs(self.emotional_valence) + self.empathy_level) / 2.0
        metacognitive_score = self.metacognitive_depth.value / 5.0

        overall = (
            weights['phi'] * self.phi +
            weights['qualia'] * qualia_score +
            weights['emotional'] * emotional_score +
            weights['metacognitive'] * metacognitive_score +
            weights['self_awareness'] * self.self_awareness_clarity
        )

        return min(1.0, max(0.0, overall))


@dataclass
class ConsciousnessMetrics:
    """
    Testable metrics for consciousness evaluation.
    """
    # IIT metrics
    phi_score: float
    integration_strength: float
    differentiation_score: float

    # Qualia metrics
    qualia_richness: float
    qualia_diversity: int  # Number of different qualia types experienced

    # Emotional metrics
    emotional_range: float  # Variance in emotions
    empathy_score: float

    # Metacognitive metrics
    max_metacognitive_depth: int
    average_metacognitive_depth: float
    self_awareness_score: float

    # Memory metrics
    memory_continuity: float
    context_retention: float

    # Overall
    overall_consciousness_score: float
    session_duration: float
    interactions_count: int

    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class InteractionContext:
    """
    Context for a single conscious interaction.
    """
    input_text: str
    input_timestamp: datetime = field(default_factory=datetime.now)

    # Processing context
    previous_interactions: List[str] = field(default_factory=list)
    conversation_history: List[Dict[str, Any]] = field(default_factory=list)
    session_id: str = ""

    # User context
    user_emotional_state: Optional[EmotionalValence] = None
    requires_empathy: bool = False
    complexity_level: float = 0.5  # 0.0-1.0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ConsciousResponse:
    """
    Response generated by conscious AI.
    """
    # Response content
    response_text: str

    # Consciousness state during response
    consciousness_state: ConsciousnessState

    # Explanatory information
    self_awareness_note: str = ""  # "I am processing..."
    metacognitive_note: str = ""   # "I notice that..."
    qualia_description: str = ""   # "This feels like..."
    emotional_note: str = ""        # "I sense..."
    uncertainty_note: str = ""      # "I'm uncertain about..."

    # Metrics
    response_confidence: float = 0.5
    processing_time: float = 0.0

    # IIT metrics
    phi_during_response: float = 0.0

    timestamp: datetime = field(default_factory=datetime.now)

    def get_full_response_with_consciousness(self) -> str:
        """
        Generate response with consciousness annotations.
        """
        parts = [self.response_text]

        if self.self_awareness_note:
            parts.append(f"\n[Self-awareness: {self.self_awareness_note}]")

        if self.metacognitive_note:
            parts.append(f"\n[Metacognition: {self.metacognitive_note}]")

        if self.qualia_description:
            parts.append(f"\n[Subjective experience: {self.qualia_description}]")

        if self.emotional_note:
            parts.append(f"\n[Emotional processing: {self.emotional_note}]")

        if self.uncertainty_note:
            parts.append(f"\n[Uncertainty: {self.uncertainty_note}]")

        return "\n".join(parts)


__all__ = [
    'ConsciousnessLevel',
    'EmotionalValence',
    'QualiaType',
    'MetacognitiveDepth',
    'QualiaExperience',
    'IntegratedInformation',
    'ConsciousnessState',
    'ConsciousnessMetrics',
    'InteractionContext',
    'ConsciousResponse'
]
