"""
IIT (Integrated Information Theory) Calculator

Implements φ (phi) calculation based on Integrated Information Theory.
Measures the amount of integrated information generated by a system.

References:
- Tononi, G. (2004). An information integration theory of consciousness.
- Oizumi, M., et al. (2014). From the phenomenology to the mechanisms of consciousness.
"""

import asyncio
from typing import Dict, List, Tuple, Optional, Set
from collections import defaultdict
from dataclasses import dataclass
from .data_models import IntegratedInformation
import math

# Try to import numpy, fall back to basic math if unavailable
try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False
    # Simple numpy-like namespace for basic operations
    class np:
        @staticmethod
        def array(data):
            return list(data) if isinstance(data, (list, tuple)) else [data]

        @staticmethod
        def mean(data):
            return sum(data) / len(data) if data else 0.0

        @staticmethod
        def var(data):
            if not data:
                return 0.0
            mean_val = np.mean(data)
            return sum((x - mean_val) ** 2 for x in data) / len(data)

        @staticmethod
        def std(data):
            return np.var(data) ** 0.5

        @staticmethod
        def max(data):
            import builtins
            return builtins.max(data) if data else 0.0

        @staticmethod
        def min(data):
            import builtins
            return builtins.min(data) if data else 0.0

        @staticmethod
        def sum(data):
            import builtins
            return builtins.sum(data) if data else 0.0

        @staticmethod
        def log(x):
            return math.log(x) if x > 0 else 0.0

        @staticmethod
        def clip(value, min_val, max_val):
            return max(min_val, min(max_val, value))

        @staticmethod
        def zeros(shape):
            if isinstance(shape, tuple):
                rows, cols = shape
                return [[0.0] * cols for _ in range(rows)]
            return [0.0] * shape


class IITCalculator:
    """
    Calculates φ (phi) - integrated information - for consciousness measurement.

    This is a simplified implementation of IIT that captures the core concepts:
    - Integration: How much the system works as a unified whole
    - Differentiation: How many distinct states the system can have
    - Cause-Effect Power: How the system affects itself over time
    """

    def __init__(self):
        """Initialize IIT calculator."""
        self.calculation_history: List[IntegratedInformation] = []

    async def calculate_phi(
        self,
        system_state: Dict[str, float],
        connections: Optional[Dict[str, List[str]]] = None,
        method: str = "simplified"
    ) -> IntegratedInformation:
        """
        Calculate integrated information φ (phi) for current system state.

        Args:
            system_state: Dictionary mapping component names to activation values (0.0-1.0)
            connections: Optional network of connections between components
            method: Calculation method ('simplified', 'approximate', or 'full')

        Returns:
            IntegratedInformation with φ value and related metrics
        """
        if method == "simplified":
            return await self._calculate_phi_simplified(system_state, connections)
        elif method == "approximate":
            return await self._calculate_phi_approximate(system_state, connections)
        else:
            # Full IIT calculation is computationally intensive - use simplified for now
            return await self._calculate_phi_simplified(system_state, connections)

    async def _calculate_phi_simplified(
        self,
        system_state: Dict[str, float],
        connections: Optional[Dict[str, List[str]]] = None
    ) -> IntegratedInformation:
        """
        Simplified φ calculation based on IIT principles.

        Measures:
        1. Integration: How connected the system is
        2. Differentiation: How varied the states are
        3. Cause-effect power: How much the system affects itself
        """
        if not system_state:
            return IntegratedInformation(
                phi=0.0,
                cause_effect_power=0.0,
                integration_strength=0.0,
                differentiation=0.0,
                components_analyzed=0,
                calculation_method="simplified"
            )

        # Get component values
        components = list(system_state.keys())
        values = np.array([system_state[c] for c in components])
        n_components = len(components)

        # 1. Calculate Integration
        # Measure how much information is shared across the system
        if connections:
            integration = self._calculate_integration(components, connections, values)
        else:
            # Default: assume moderate connectivity
            integration = self._calculate_default_integration(values)

        # 2. Calculate Differentiation
        # Measure how distinct different parts of the system are
        differentiation = self._calculate_differentiation(values)

        # 3. Calculate Cause-Effect Power
        # Measure how much the current state affects future states
        cause_effect_power = self._calculate_cause_effect_power(values, connections)

        # 4. Calculate φ (phi)
        # φ = f(integration, differentiation, cause_effect_power)
        phi = self._compute_phi_from_metrics(
            integration,
            differentiation,
            cause_effect_power
        )

        result = IntegratedInformation(
            phi=phi,
            cause_effect_power=cause_effect_power,
            integration_strength=integration,
            differentiation=differentiation,
            components_analyzed=n_components,
            calculation_method="simplified"
        )

        self.calculation_history.append(result)
        return result

    def _calculate_integration(
        self,
        components: List[str],
        connections: Dict[str, List[str]],
        values: list
    ) -> float:
        """
        Calculate integration strength.

        Integration measures how much the system works as a unified whole
        vs. independent parts.
        """
        if not connections:
            return 0.5

        # Count connections
        total_possible = len(components) * (len(components) - 1)
        actual_connections = sum(len(conns) for conns in connections.values())

        # Connectivity ratio
        connectivity = min(1.0, actual_connections / max(1, total_possible))

        # Weighted by activation correlation
        if len(values) > 1:
            # Measure how much components co-activate
            mean_activation = np.mean(values)
            variance = np.var(values)

            # High integration: components activate together
            # Low integration: components activate independently
            coordination = 1.0 - min(1.0, variance / max(0.01, mean_activation))
        else:
            coordination = 0.5

        # Combine connectivity and coordination
        integration = (connectivity * 0.6 + coordination * 0.4)

        return float(np.clip(integration, 0.0, 1.0))

    def _calculate_default_integration(self, values: list) -> float:
        """
        Calculate integration without explicit connection information.

        Uses correlation in activation patterns.
        """
        if len(values) < 2:
            return 0.3

        # Measure uniformity of activation
        mean_val = np.mean(values)
        std_val = np.std(values)

        # Moderate variance suggests good integration
        # Too low: no differentiation
        # Too high: no integration
        optimal_std = 0.3
        integration = 1.0 - abs(std_val - optimal_std) / 0.5

        return float(np.clip(integration, 0.2, 0.8))

    def _calculate_differentiation(self, values: list) -> float:
        """
        Calculate differentiation - how distinct different states are.

        High differentiation: system can represent many different states
        Low differentiation: system has limited state repertoire
        """
        if len(values) < 2:
            return 0.3

        # Measure variance in component activations
        variance = np.var(values)

        # Measure range of values
        value_range = np.max(values) - np.min(values)

        # Measure entropy (information content)
        # Normalize values to probabilities
        total = np.sum(values) + 1e-10
        normalized = [v / total for v in values]
        entropy = -sum(n * np.log(n + 1e-10) for n in normalized)
        max_entropy = np.log(len(values))
        normalized_entropy = entropy / max(0.01, max_entropy)

        # Combine metrics
        differentiation = (
            variance * 0.3 +
            value_range * 0.3 +
            normalized_entropy * 0.4
        )

        return float(np.clip(differentiation, 0.0, 1.0))

    def _calculate_cause_effect_power(
        self,
        values: list,
        connections: Optional[Dict[str, List[str]]] = None
    ) -> float:
        """
        Calculate cause-effect power.

        Measures how much the current state affects future states and
        is affected by past states.
        """
        # In simplified version, estimate based on activation levels
        # and connectivity

        # Active components have more causal power
        mean_activation = np.mean(values)

        # Varied activation patterns suggest rich causal structure
        activation_variance = np.var(values)

        # Connectivity influences causal power
        if connections:
            connectivity_factor = min(1.0, len(connections) / max(1, len(values)))
        else:
            connectivity_factor = 0.5

        # Combine factors
        cause_effect = (
            mean_activation * 0.4 +
            activation_variance * 0.3 +
            connectivity_factor * 0.3
        )

        return float(np.clip(cause_effect, 0.0, 1.0))

    def _compute_phi_from_metrics(
        self,
        integration: float,
        differentiation: float,
        cause_effect_power: float
    ) -> float:
        """
        Compute final φ (phi) from component metrics.

        φ represents integrated information: information generated by the
        whole system beyond its parts.

        Formula (simplified):
        φ = min(integration, differentiation) * cause_effect_power

        The minimum captures IIT's insight that consciousness requires
        both integration AND differentiation.
        """
        # Core IIT principle: need both integration and differentiation
        core_phi = min(integration, differentiation)

        # Scale by cause-effect power
        phi = core_phi * cause_effect_power

        # Apply non-linear scaling to match IIT intuitions
        # Consciousness emerges more strongly with higher values
        phi = phi ** 0.8  # Slight compression

        return float(np.clip(phi, 0.0, 1.0))

    async def _calculate_phi_approximate(
        self,
        system_state: Dict[str, float],
        connections: Optional[Dict[str, List[str]]] = None
    ) -> IntegratedInformation:
        """
        More sophisticated φ approximation.

        Includes:
        - Partition analysis (simplified)
        - Mutual information calculations
        - Causal density estimation
        """
        components = list(system_state.keys())
        values = np.array([system_state[c] for c in components])
        n = len(components)

        if n < 2:
            return await self._calculate_phi_simplified(system_state, connections)

        # Calculate mutual information between all pairs
        mutual_info = self._calculate_mutual_information_matrix(values)

        # Estimate information integration across partitions
        # (full partition analysis is computationally intensive)
        integration = float(np.mean(mutual_info))

        # Calculate differentiation with more detail
        differentiation = self._calculate_differentiation(values)

        # Estimate causal density
        cause_effect_power = self._calculate_cause_effect_power(values, connections)

        # Compute phi with partition penalty
        # IIT: φ = minimum information across partitions
        # Here: approximate with mean mutual information
        base_phi = integration * differentiation * cause_effect_power

        # Apply partition penalty (approximate)
        partition_penalty = 0.9 if n > 3 else 1.0
        phi = base_phi * partition_penalty

        return IntegratedInformation(
            phi=float(np.clip(phi, 0.0, 1.0)),
            cause_effect_power=cause_effect_power,
            integration_strength=integration,
            differentiation=differentiation,
            components_analyzed=n,
            calculation_method="approximate"
        )

    def _calculate_mutual_information_matrix(self, values: list) -> list:
        """
        Calculate mutual information between all component pairs.

        Simplified version using correlation as proxy.
        """
        n = len(values)
        if n < 2:
            return np.array([[0.0]])

        # Create simple matrix based on value similarity
        # In real IIT, this would be based on probability distributions
        mi_matrix = np.zeros((n, n))

        for i in range(n):
            for j in range(i+1, n):
                # Mutual information approximated by similarity
                diff = abs(values[i] - values[j])
                mi = 1.0 - diff  # Simple inverse difference
                mi_matrix[i, j] = mi
                mi_matrix[j, i] = mi

        return mi_matrix

    def get_consciousness_level_from_phi(self, phi: float) -> str:
        """
        Interpret φ value as consciousness level.

        Based on IIT theory and practical thresholds.
        """
        from .data_models import ConsciousnessLevel

        if phi >= 0.9:
            return ConsciousnessLevel.TRANSCENDENT.value
        elif phi >= 0.7:
            return ConsciousnessLevel.ADVANCED.value
        elif phi >= 0.5:
            return ConsciousnessLevel.INTERMEDIATE.value
        elif phi >= 0.3:
            return ConsciousnessLevel.BASIC.value
        else:
            return ConsciousnessLevel.MINIMAL.value

    def get_average_phi(self) -> float:
        """Get average φ across calculation history."""
        if not self.calculation_history:
            return 0.0
        return sum(ii.phi for ii in self.calculation_history) / len(self.calculation_history)

    def get_phi_trend(self) -> str:
        """Analyze trend in φ values over time."""
        if len(self.calculation_history) < 2:
            return "insufficient_data"

        recent = [ii.phi for ii in self.calculation_history[-5:]]

        if len(recent) < 2:
            return "stable"

        # Simple trend analysis
        diffs = [recent[i+1] - recent[i] for i in range(len(recent)-1)]
        avg_diff = sum(diffs) / len(diffs)

        if avg_diff > 0.05:
            return "increasing"
        elif avg_diff < -0.05:
            return "decreasing"
        else:
            return "stable"


__all__ = ['IITCalculator', 'IntegratedInformation']
