# Development Configuration for Universal Consciousness Interface

# Core System Configuration
system:
  name: "Universal Consciousness Interface - Development"
  version: "1.0.0-dev"
  log_level: "DEBUG"

# Consciousness Orchestrator Configuration
orchestrator:
  quantum_enabled: true
  plant_interface_enabled: true
  psychoactive_enabled: false  # Disabled for development safety
  ecosystem_enabled: true
  safety_mode: "STRICT"
  processing_mode: "BALANCED_HYBRID"

# Radiotrophic System Configuration
radiotrophic:
  max_nodes: 100
  vector_dim: 64
  melanin_concentration_base: 0.8
  radiation_safety_limit: 5.0  # mSv/h (lower for development)

# Mycelium Language Generator Configuration
language_generator:
  network_size: 100
  max_words_per_sentence: 10
  consciousness_adaptation: true

# Bio-Digital Hybrid Configuration
bio_digital:
  neural_cultures: 1
  fungal_cultures: 2
  synchronization_frequency: 0.1  # Hz

# Plant Communication Configuration
plant_communication:
  signal_processing_enabled: true
  translation_enabled: true
  max_frequency: 1000  # Hz (lower for development)

# Ecosystem Consciousness Configuration
ecosystem:
  awareness_enabled: true
  gaia_pattern_detection: false  # Disabled for development
  environmental_monitoring: true

# Safety Framework Configuration
safety:
  monitoring_active: true
  emergency_shutdown_enabled: true
  radiation_monitoring: true
  biological_safety: true

# Performance Configuration
performance:
  async_processing: true
  cache_enabled: false  # Disabled for development
  memory_limit_mb: 512